import { MY_SQL_DB_CONNECTION_LIMIT, MY_SQL_DB_DATABASE, MY_SQL_DB_HOST, MY_SQL_DB_PASSWORD, MY_SQL_DB_PORT, MY_SQL_DB_USER } from "../environment";

export const DATA_SOURCES = {
    mySqlDataSource: {
        DB_HOST: MY_SQL_DB_HOST,
        DB_USER: MY_SQL_DB_USER,
        DB_PASSWORD: MY_SQL_DB_PASSWORD,
        DB_PORT: MY_SQL_DB_PORT,
        DB_DATABASE: MY_SQL_DB_DATABASE,
        DB_CONNECTION_LIMIT: MY_SQL_DB_CONNECTION_LIMIT ? parseInt(MY_SQL_DB_CONNECTION_LIMIT) : 4,
    }
};